# -*- coding: utf-8 -*-
"""Spandana_macherla.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMrkAS5tUNLuvt_bp_fSH6t358CAd5hg
"""

# ============================================================
# Reinforcement Learning Project Part 2
# Q-Learning for Solving a Grid Maze
# Student: Spandan Macherla
# Course: Applied Machine Intelligence and Reinforcement Learning
# ============================================================

import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1. PARAMETERS
# ============================================================

GRID_SIZE = 5

LEARNING_RATE = 0.10
DISCOUNT_FACTOR = 0.95

INITIAL_EPSILON = 1.00
MIN_EPSILON = 0.01
EPSILON_DECAY = 0.995

TRAINING_EPISODES = 1000
MAX_STEPS = 200

# Rewards
GOAL_REWARD = 100
MOVE_REWARD = -1
OBSTACLE_REWARD = -10
INVALID_REWARD = -10

# Actions
UP = 0
DOWN = 1
LEFT = 2
RIGHT = 3

ACTIONS = [UP, DOWN, LEFT, RIGHT]

ACTION_NAMES = {
    UP: "Up",
    DOWN: "Down",
    LEFT: "Left",
    RIGHT: "Right"
}

# ============================================================
# 2. MAZE DEFINITION
# ============================================================

# Start position
START = (0, 0)

# Goal position
GOAL = (4, 4)

# Obstacles
OBSTACLES = {
    (0, 3),
    (1, 0),
    (1, 2),
    (2, 4),
    (3, 1),
    (3, 2)
}

# ============================================================
# 3. ENVIRONMENT FUNCTIONS
# ============================================================

def state_to_index(state):
    """
    Convert row and column into a single state index.
    """
    row, col = state
    return row * GRID_SIZE + col


def index_to_state(index):
    """
    Convert state index back to row and column.
    """
    row = index // GRID_SIZE
    col = index % GRID_SIZE
    return (row, col)


def reset_environment():
    """
    Reset the environment to the starting position.
    """
    return START


def take_action(state, action):
    """
    Execute an action and return:
    next_state, reward, done
    """

    row, col = state

    if action == UP:
        new_row = row - 1
        new_col = col

    elif action == DOWN:
        new_row = row + 1
        new_col = col

    elif action == LEFT:
        new_row = row
        new_col = col - 1

    elif action == RIGHT:
        new_row = row
        new_col = col + 1

    else:
        return state, INVALID_REWARD, False

    # Check grid boundaries
    if (
        new_row < 0
        or new_row >= GRID_SIZE
        or new_col < 0
        or new_col >= GRID_SIZE
    ):
        return state, INVALID_REWARD, False

    next_state = (new_row, new_col)

    # Check obstacle
    if next_state in OBSTACLES:
        return state, OBSTACLE_REWARD, False

    # Check goal
    if next_state == GOAL:
        return next_state, GOAL_REWARD, True

    # Normal movement
    return next_state, MOVE_REWARD, False


# ============================================================
# 4. EPSILON-GREEDY ACTION SELECTION
# ============================================================

def choose_action(q_table, state, epsilon):
    """
    Select an action using epsilon-greedy exploration.
    """

    state_index = state_to_index(state)

    # Exploration
    if np.random.random() < epsilon:
        return np.random.choice(ACTIONS)

    # Exploitation
    q_values = q_table[state_index]

    max_q = np.max(q_values)

    # Handle ties randomly
    best_actions = np.where(q_values == max_q)[0]

    return np.random.choice(best_actions)


# ============================================================
# 5. TRAINING FUNCTION
# ============================================================

def train_q_learning(seed=123):
    """
    Train a Q-learning agent.
    """

    np.random.seed(seed)

    # 25 states x 4 actions
    q_table = np.zeros((GRID_SIZE * GRID_SIZE, 4))

    episode_rewards = []
    episode_steps = []
    episode_success = []
    epsilon_values = []

    epsilon = INITIAL_EPSILON

    for episode in range(TRAINING_EPISODES):

        state = reset_environment()

        total_reward = 0
        steps = 0
        success = False

        for step in range(MAX_STEPS):

            steps += 1

            # Select action
            action = choose_action(
                q_table,
                state,
                epsilon
            )

            # Take action
            next_state, reward, done = take_action(
                state,
                action
            )

            current_index = state_to_index(state)
            next_index = state_to_index(next_state)

            # Current Q-value
            current_q = q_table[current_index, action]

            # Maximum future Q-value
            if done:
                max_future_q = 0
            else:
                max_future_q = np.max(q_table[next_index])

            # Q-learning update
            new_q = current_q + LEARNING_RATE * (
                reward
                + DISCOUNT_FACTOR * max_future_q
                - current_q
            )

            q_table[current_index, action] = new_q

            # Update state
            state = next_state

            total_reward += reward

            if done:
                success = True
                break

        # Store results
        episode_rewards.append(total_reward)
        episode_steps.append(steps)
        episode_success.append(1 if success else 0)
        epsilon_values.append(epsilon)

        # Decay epsilon
        epsilon = max(
            MIN_EPSILON,
            epsilon * EPSILON_DECAY
        )

    return (
        q_table,
        episode_rewards,
        episode_steps,
        episode_success,
        epsilon_values
    )


# ============================================================
# 6. TRAIN THE MAIN MODEL
# ============================================================

q_table, rewards, steps, successes, epsilons = train_q_learning(
    seed=123
)

print("=" * 60)
print("Q-LEARNING TRAINING COMPLETED")
print("=" * 60)

print("Training Episodes:", TRAINING_EPISODES)
print("Learning Rate:", LEARNING_RATE)
print("Discount Factor:", DISCOUNT_FACTOR)
print("Initial Epsilon:", INITIAL_EPSILON)
print("Minimum Epsilon:", MIN_EPSILON)
print("Epsilon Decay:", EPSILON_DECAY)

# ============================================================
# 7. TRAINING RESULTS
# ============================================================

first_100_success = np.mean(successes[:100]) * 100
last_100_success = np.mean(successes[-100:]) * 100

first_100_reward = np.mean(rewards[:100])
last_100_reward = np.mean(rewards[-100:])

first_100_steps = np.mean(steps[:100])
last_100_steps = np.mean(steps[-100:])

print("\nTRAINING PERFORMANCE")
print("-" * 60)

print(
    f"First 100 Episodes Success Rate: "
    f"{first_100_success:.2f}%"
)

print(
    f"Last 100 Episodes Success Rate: "
    f"{last_100_success:.2f}%"
)

print(
    f"First 100 Episodes Average Reward: "
    f"{first_100_reward:.2f}"
)

print(
    f"Last 100 Episodes Average Reward: "
    f"{last_100_reward:.2f}"
)

print(
    f"First 100 Episodes Average Steps: "
    f"{first_100_steps:.2f}"
)

print(
    f"Last 100 Episodes Average Steps: "
    f"{last_100_steps:.2f}"
)

# ============================================================
# 8. MOVING AVERAGE
# ============================================================

def moving_average(values, window=50):

    values = np.array(values)

    return np.convolve(
        values,
        np.ones(window) / window,
        mode="valid"
    )


reward_moving_average = moving_average(
    rewards,
    50
)

success_moving_average = moving_average(
    successes,
    50
)

# ============================================================
# 9. TRAINING GRAPHS
# ============================================================
# These graphs are for analysis only.
# They do not need to be included in the PowerPoint
# because you requested a presentation without graphs.

plt.figure(figsize=(10, 5))

plt.plot(
    rewards,
    alpha=0.3,
    label="Episode Reward"
)

plt.plot(
    range(49, len(rewards)),
    reward_moving_average,
    label="50-Episode Moving Average"
)

plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.title("Q-Learning Training Reward")
plt.legend()
plt.grid(True)

plt.show()


plt.figure(figsize=(10, 5))

plt.plot(
    range(49, len(successes)),
    success_moving_average * 100
)

plt.xlabel("Episode")
plt.ylabel("Success Rate (%)")
plt.title("Q-Learning Success Rate")
plt.grid(True)

plt.show()


plt.figure(figsize=(10, 5))

plt.plot(
    epsilons
)

plt.xlabel("Episode")
plt.ylabel("Epsilon")
plt.title("Epsilon Decay During Training")
plt.grid(True)

plt.show()

# ============================================================
# 10. GREEDY POLICY
# ============================================================

def get_greedy_action(q_table, state):

    state_index = state_to_index(state)

    q_values = q_table[state_index]

    return int(np.argmax(q_values))


def get_greedy_path(q_table):

    state = START

    path = [state]

    actions_taken = []

    visited = set()

    for step in range(MAX_STEPS):

        if state == GOAL:
            break

        # Prevent infinite loops
        if state in visited:
            break

        visited.add(state)

        action = get_greedy_action(
            q_table,
            state
        )

        next_state, reward, done = take_action(
            state,
            action
        )

        actions_taken.append(
            ACTION_NAMES[action]
        )

        path.append(next_state)

        state = next_state

        if done:
            break

    return path, actions_taken


# ============================================================
# 11. DISPLAY LEARNED POLICY
# ============================================================

path, actions_taken = get_greedy_path(q_table)

print("\nLEARNED GREEDY POLICY")
print("=" * 60)

print("Starting State:", START)
print("Goal State:", GOAL)

print("\nActions Taken:")

for i, action in enumerate(actions_taken, start=1):
    print(
        f"Step {i}: {action}"
    )

print("\nPath:")

for i, position in enumerate(path):
    print(
        f"{i}: {position}"
    )

if path[-1] == GOAL:
    print("\nResult: Goal reached successfully.")
else:
    print("\nResult: Goal was not reached.")

print(
    "Number of Steps:",
    len(actions_taken)
)

# ============================================================
# 12. EVALUATION FUNCTION
# ============================================================

def evaluate_agent(
    q_table,
    evaluation_episodes=100
):

    evaluation_rewards = []
    evaluation_steps = []
    evaluation_success = []

    for episode in range(evaluation_episodes):

        state = reset_environment()

        total_reward = 0
        steps = 0
        success = False

        for step in range(MAX_STEPS):

            steps += 1

            # No exploration during evaluation
            action = get_greedy_action(
                q_table,
                state
            )

            next_state, reward, done = take_action(
                state,
                action
            )

            total_reward += reward

            state = next_state

            if done:
                success = True
                break

        evaluation_rewards.append(
            total_reward
        )

        evaluation_steps.append(
            steps
        )

        evaluation_success.append(
            1 if success else 0
        )

    return (
        evaluation_rewards,
        evaluation_steps,
        evaluation_success
    )


# ============================================================
# 13. FINAL EVALUATION
# ============================================================

evaluation_rewards, evaluation_steps, evaluation_success = evaluate_agent(
    q_table,
    evaluation_episodes=100
)

evaluation_success_rate = (
    np.mean(evaluation_success) * 100
)

successful_steps = [
    evaluation_steps[i]
    for i in range(len(evaluation_success))
    if evaluation_success[i] == 1
]

successful_rewards = [
    evaluation_rewards[i]
    for i in range(len(evaluation_success))
    if evaluation_success[i] == 1
]

if len(successful_steps) > 0:

    average_successful_steps = np.mean(
        successful_steps
    )

    average_successful_reward = np.mean(
        successful_rewards
    )

else:

    average_successful_steps = 0

    average_successful_reward = 0


print("\n")
print("=" * 60)
print("FINAL EVALUATION")
print("=" * 60)

print(
    f"Evaluation Episodes: 100"
)

print(
    f"Success Rate: "
    f"{evaluation_success_rate:.2f}%"
)

print(
    f"Average Successful Steps: "
    f"{average_successful_steps:.2f}"
)

print(
    f"Average Successful Reward: "
    f"{average_successful_reward:.2f}"
)

# ============================================================
# 14. MULTIPLE TRAINING RUNS
# ============================================================

def run_validation(seed):

    (
        validation_q,
        validation_rewards,
        validation_steps,
        validation_success,
        validation_epsilon
    ) = train_q_learning(seed)

    (
        test_rewards,
        test_steps,
        test_success
    ) = evaluate_agent(
        validation_q,
        evaluation_episodes=100
    )

    success_rate = (
        np.mean(test_success) * 100
    )

    successful_steps = [
        test_steps[i]
        for i in range(len(test_success))
        if test_success[i] == 1
    ]

    successful_rewards = [
        test_rewards[i]
        for i in range(len(test_success))
        if test_success[i] == 1
    ]

    if len(successful_steps) > 0:

        avg_steps = np.mean(
            successful_steps
        )

        avg_reward = np.mean(
            successful_rewards
        )

    else:

        avg_steps = 0
        avg_reward = 0

    return (
        success_rate,
        avg_steps,
        avg_reward
    )


# Three validation runs
validation_seeds = [123, 456, 789]

validation_results = []

for seed in validation_seeds:

    result = run_validation(seed)

    validation_results.append(result)


print("\n")
print("=" * 60)
print("MULTIPLE-RUN VALIDATION")
print("=" * 60)

print(
    f"{'Run':<10}"
    f"{'Success Rate':<20}"
    f"{'Avg Steps':<20}"
    f"{'Avg Reward':<20}"
)

for i, result in enumerate(
    validation_results,
    start=1
):

    success_rate, avg_steps, avg_reward = result

    print(
        f"{i:<10}"
        f"{success_rate:.2f}%{'':<14}"
        f"{avg_steps:.2f}{'':<14}"
        f"{avg_reward:.2f}"
    )


# ============================================================
# 15. VALIDATION MEANS AND STANDARD DEVIATIONS
# ============================================================

success_rates = [
    result[0]
    for result in validation_results
]

average_steps = [
    result[1]
    for result in validation_results
]

average_rewards = [
    result[2]
    for result in validation_results
]

print("\nVALIDATION SUMMARY")
print("-" * 60)

print(
    f"Mean Success Rate: "
    f"{np.mean(success_rates):.2f}%"
)

print(
    f"Standard Deviation of Success Rate: "
    f"{np.std(success_rates):.2f}"
)

print(
    f"Mean Successful Steps: "
    f"{np.mean(average_steps):.2f}"
)

print(
    f"Standard Deviation of Steps: "
    f"{np.std(average_steps):.2f}"
)

print(
    f"Mean Successful Reward: "
    f"{np.mean(average_rewards):.2f}"
)

print(
    f"Standard Deviation of Reward: "
    f"{np.std(average_rewards):.2f}"
)

# ============================================================
# 16. Q-TABLE DISPLAY
# ============================================================

print("\n")
print("=" * 60)
print("FINAL Q-TABLE")
print("=" * 60)

print(
    f"{'State':<10}"
    f"{'Up':<15}"
    f"{'Down':<15}"
    f"{'Left':<15}"
    f"{'Right':<15}"
)

for state_index in range(GRID_SIZE * GRID_SIZE):

    state = index_to_state(state_index)

    # Do not display obstacle states
    if state in OBSTACLES:
        continue

    values = q_table[state_index]

    print(
        f"{str(state):<10}"
        f"{values[UP]:<15.2f}"
        f"{values[DOWN]:<15.2f}"
        f"{values[LEFT]:<15.2f}"
        f"{values[RIGHT]:<15.2f}"
    )

# ============================================================
# 17. FINAL PROJECT SUMMARY
# ============================================================

print("\n")
print("=" * 60)
print("PROJECT SUMMARY")
print("=" * 60)

print("Algorithm: Tabular Q-Learning")
print("Environment: 5 x 5 Grid Maze")
print("Training Episodes:", TRAINING_EPISODES)
print("Learning Rate:", LEARNING_RATE)
print("Discount Factor:", DISCOUNT_FACTOR)
print("Initial Epsilon:", INITIAL_EPSILON)
print("Minimum Epsilon:", MIN_EPSILON)
print("Epsilon Decay:", EPSILON_DECAY)

print(
    f"\nFinal Evaluation Success Rate: "
    f"{evaluation_success_rate:.2f}%"
)

print(
    f"Final Average Successful Steps: "
    f"{average_successful_steps:.2f}"
)

print(
    f"Final Average Successful Reward: "
    f"{average_successful_reward:.2f}"
)

print(
    "\nThe Q-learning agent was trained through repeated "
    "interaction with the grid maze and evaluated using "
    "the learned greedy policy."
)

